### PR TITLE
use printf to pretty print commands

### PR DESCRIPTION
**Pull request by joshblum**
Addresses #3. Example output below:

screen shot 2015-06-11 at 1 00 07 pm

### CODE REVIEW

**Comment by Vaelatern** [comment]
Does this go to stdout? It may be useful to put this in the echoerr function so as to generalize it. Thoughts?

**Comment by Vaelatern** [comment]
It occurs to me that this may not make the config file look right. Can you test this by commenting out the three lines that are 

```
if [ -h $fullname ]; then
    continue;
fi
```

**Comment by joshblum** [comment]
`printf` prints to stdout by defualt, but we can put it into a variable too: http://wiki.bash-hackers.org/commands/builtin/printf

a `printferr` function is fine.

commenting the lines didn't make a difference with the output..

**Comment by Vaelatern** [comment]
The issue I see is we don't detect any files in that same configuration, it seems. I don't know that the indentation won't look wildly off.

One fix would be to replace the contents of the configuration with [Configuration Goes Here] or some such.

**Comment by joshblum** [comment]
screen shot 2015-06-11 at 9 08 14 pm

Hmm it seems to work fine for me..

**Pull request merged**
